name: "Conventional Commits Stats"

on:
  schedule:
    - cron: '0 0 * * *' # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente pelo painel do GitHub

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Commit Chart
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_REPOSITORY_METRICS }}
          base: header, activity, community, repositories
          
          # Mostra as linguagens mais usadas
          plugin_languages: yes
          plugin_languages_sections: most-used
          
          # Ativa o histórico de linhas e commits detalhados
          plugin_lines: yes
          plugin_lines_sections: history # <--- Força o gráfico a criar a seção de histórico
          plugin_lines_delay: 10
